future: true
permalink: /:title/
url: https://starthemoon.github.io/categories/
name: starthemoon
author: starthemoon
qq: 812138420
email: 15331309@mail2.sysu.edu.cn

duoshuo: 魏兆
beian: 
cnzz: 
weibo: 
github: starthemoon
about: "这里是starthemoon的个人博客，创建于 2018 年。"

safe: false
paginate: 20

theme: jekyll-theme-hacker